import { EURO, INDUSTRY } from "./constants";
import { FaSkiingNordic } from "react-icons/fa";
export const TABLE_VIEW = "table_view";
export const ANMITION_VIEW = "animation_view";
export const DELIVERY = [
  [
    {
      id: 1,
      packagingId: EURO,
      packagingName: "Euro",
      width: 1200,
      length: 800,
      productName: "Flachakanne",
      productId: "1",
      threeInRow: true,
      quantity: 2,
      factoryId: 1,
      factoryName: "Werk Nord",
      buildingId: 1,
      buildingName: "A1",
      rowId: "1",
      rowName: "B01",
    },
    {
      id: 1,
      packagingId: EURO,
      packagingName: "Euro",
      width: 1200,
      length: 800,
      productName: "Flachakanne",
      productId: "1",
      threeInRow: true,
      quantity: 2,
      factoryId: 1,
      factoryName: "Werk Nord",
      buildingId: 1,
      buildingName: "A1",
      rowId: "2",
      rowName: "B02",
    },
    // {
    //   id: 3,
    //   packagingId: INDUSTRY,
    //   productName: "y",
    //   quantity: 5,
    //   buildingId: 1,
    //   factoryId: 1,
    // },
    // {
    //   id: 4,
    //   packagingId: EURO,
    //   productName: "Flachakanne",
    //   productId: "1",
    //   quantity: 1,
    //   buildingId: 1,
    //   factoryId: 2,
    // },
    // {
    //   id: 5,
    //   packagingId: EURO,
    //   productName: "Flachakanne",
    //   productId: "1",
    //   quantity: 4,
    //   buildingId: 1,
    //   factoryId: 2,
    // },
    // {
    //   id: 3,
    //   packagingId: INDUSTRY,
    //   productName: "Flachakanne",
    //   productId: "1",
    //   quantity: 1,
    //   buildingId: 1,
    //   factoryId: 2,
    // },
    // {
    //   id: 7,
    //   packagingId: EURO,
    //   productName: "Flachakanne",
    //   productId: "1",
    //   quantity: 1,
    //   buildingId: 1,
    //   factoryId: 2,
    // },
    // {
    //   id: 8,
    //   packagingId: EURO,
    //   productName: "Flachakanne",
    //   productId: "1",
    //   quantity: 1,
    //   buildingId: 1,
    //   factoryId: 2,
    // },
    // {
    //   id: 9,
    //   packagingId: EURO,
    //   productName: "Flachakanne",
    //   productId: "1",
    //   quantity: 5,
    //   buildingId: 1,
    //   factoryId: 2,
    // },
    // {
    //   id: 1,
    //   packagingId: INDUSTRY,
    //   productName: "Flachakanne",
    //   productId: "1",
    //   quantity: 1,
    //   buildingId: 1,
    //   factoryId: 2,
    // },
  ],
  // [
  //   ({ id: 1, packagingId: EURO, productName: "Flachakanne", productId : "1",  quantity: 1, buildingId: 1, factoryId: 1 },
  //   { id: 1, packagingId: EURO, productName: "Flachakanne", productId : "1",  quantity: 1, buildingId: 1, factoryId: 1 },
  //   { id: 1, packagingId: INDUSTRY, productName: "y", quantity: 1, buildingId: 1, factoryId: 1 },
  //   { id: 1, packagingId: EURO, productName: "Flachakanne", productId : "1",  quantity: 1, buildingId: 1, factoryId: 2 },
  //   { id: 1, packagingId: EURO, productName: "Flachakanne", productId : "1",  quantity: 1, buildingId: 1, factoryId: 2 },
  //   { id: 1, packagingId: EURO, productName: "Flachakanne", productId : "1",  quantity: 1, buildingId: 1, factoryId: 2 },
  //   { id: 1, packagingId: EURO, productName: "Flachakanne", productId : "1",  quantity: 1, buildingId: 1, factoryId: 2 },
  //   { id: 1, packagingId: EURO, productName: "Flachakanne", productId : "1",  quantity: 1, buildingId: 1, factoryId: 2 },
  //   { id: 1, packagingId: EURO, productName: "Flachakanne", productId : "1",  quantity: 1, buildingId: 1, factoryId: 2 },
  //   { id: 1, packagingId: INDUSTRY, productName: "Flachakanne", productId : "1",  quantity: 1, buildingId: 1, factoryId: 2 }),
  // ],

  // [
  //   // { id: 1, packagingId: EURO, productName: "Flachakanne", productId : "1",  quantity: 1, buildingId: 1, factoryId: 1 },
  //   { id: 1, packagingId: EURO, productName: "Flachakanne", productId : "1",  quantity: 4, buildingId: 1, factoryId: 1 },
  //   { id: 1, packagingId: INDUSTRY, productName: "y", quantity: 2, buildingId: 1, factoryId: 1 },
  //   { id: 1, packagingId: INDUSTRY, productName: "y", quantity: 2, buildingId: 1, factoryId: 1 },
  //   { id: 1, packagingId: INDUSTRY, productName: "y", quantity: 1, buildingId: 1, factoryId: 1 },
  //   { id: 1, packagingId: EURO, productName: "Flachakanne", productId : "1",  quantity: 1, buildingId: 1, factoryId: 2 },
  //   { id: 1, packagingId: EURO, productName: "Flachakanne", productId : "1",  quantity: 1, buildingId: 1, factoryId: 2 },
  //   { id: 1, packagingId: EURO, productName: "Flachakanne", productId : "1",  quantity: 1, buildingId: 1, factoryId: 2 },
  //   { id: 1, packagingId: EURO, productName: "Flachakanne", productId : "1",  quantity: 1, buildingId: 1, factoryId: 2 },
  //   { id: 1, packagingId: INDUSTRY, productName: "Flachakanne", productId : "1",  quantity: 1, buildingId: 1, factoryId: 2 },
  // ],
  // [
  //   ({ id: 1, packagingId: EURO, productName: "Flachakanne", productId : "1",  quantity: 3, buildingId: 1, factoryId: 1 },
  //   { id: 2, packagingId: EURO, productName: "Flachakanne", productId : "1",  quantity: 1, buildingId: 1, factoryId: 1 },
  //   { id: 3, packagingId: INDUSTRY, productName: "y", quantity: 5, buildingId: 1, factoryId: 1 },
  //   { id: 4, packagingId: EURO, productName: "Flachakanne", productId : "1",  quantity: 1, buildingId: 1, factoryId: 2 },
  //   { id: 5, packagingId: EURO, productName: "Flachakanne", productId : "1",  quantity: 1, buildingId: 1, factoryId: 2 },
  //   { id: 3, packagingId: INDUSTRY, productName: "Flachakanne", productId : "1",  quantity: 1, buildingId: 1, factoryId: 2 },
  //   { id: 7, packagingId: EURO, productName: "Flachakanne", productId : "1",  quantity: 1, buildingId: 1, factoryId: 2 },
  //   { id: 8, packagingId: EURO, productName: "Flachakanne", productId : "1",  quantity: 1, buildingId: 1, factoryId: 2 },
  //   { id: 9, packagingId: EURO, productName: "Flachakanne", productId : "1",  quantity: 5, buildingId: 1, factoryId: 2 }),
  //   // { id: 1, packagingId: INDUSTRY, : "Flachakanne", quantity: 1, buildingId: 1, factoryId: 2 }
  // ],
];
