export const SET_CUSTOMER = "SET_CUSTOMER";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_STORAGE = "SET_STORAGE";
export const SET_STORAGE_BRIDGES = "SET_STORAGE_BRIDGES";
export const SET_EMPLOYEES = "SET_EMPLOYEES";
