export const test_storage = {
  1: {
    compartment: "comp_1",
    stock: 9,
    maxStock: 30,
    width: 5,
    warehouse: 1,
    id: 1,
  },
  2: {
    compartment: "comp_1",
    stock: 0,
    maxStock: 30,
    width: 5,
    warehouse: 1,
    id: 2,
  },
  3: {
    compartment: "comp_1",
    stock: 20,
    maxStock: 30,
    width: 5,
    warehouse: 1,
    id: 3,
  },
  4: {
    compartment: "comp_1",
    stock: 9,
    maxStock: 30,
    width: 5,
    warehouse: 1,
    id: 4,
  },
  5: {
    compartment: "comp_1",
    stock: 10,
    maxStock: 30,
    width: 5,
    warehouse: 1,
    id: 5,
  },
  6: {
    compartment: "comp_1",
    stock: 20,
    maxStock: 30,
    width: 5,
    warehouse: 1,
    id: 6,
  },
  7: {
    compartment: "comp_1",
    stock: 20,
    maxStock: 30,
    width: 5,
    warehouse: 1,
    id: 7,
  },

  8: {
    compartment: "comp_2",
    stock: 0,
    maxStock: 30,
    width: 5,
    warehouse: 1,
    id: 8,
  },
  9: {
    compartment: "comp_2",
    stock: 30,
    maxStock: 30,
    width: 5,
    warehouse: 1,
    id: 9,
  },
  10: {
    compartment: "comp_2",
    stock: 10,
    maxStock: 30,
    width: 5,
    warehouse: 1,
    id: 10,
  },
  11: {
    compartment: "comp_2",
    stock: 20,
    maxStock: 30,
    width: 5,
    warehouse: 1,
    id: 11,
  },
  12: {
    compartment: "comp_2",
    stock: 20,
    maxStock: 30,
    width: 5,
    warehouse: 1,
    id: 12,
  },

  13: {
    compartment: "comp_2",
    stock: 20,
    maxStock: 30,
    width: 5,
    warehouse: 1,
    id: 13,
  },

  14: {
    compartment: "comp_2",
    stock: 20,
    maxStock: 30,
    width: 5,
    warehouse: 1,
    id: 14,
  },

  15: {
    compartment: "comp_3",
    stock: 20,
    maxStock: 30,
    width: 2,
    warehouse: 1,
    id: 13,
  },

  16: {
    compartment: "comp_3",
    stock: 20,
    maxStock: 30,
    width: 2,
    warehouse: 1,
    id: 16,
  },

  17: {
    compartment: "comp_3",
    stock: 20,
    maxStock: 30,
    width: 2,
    warehouse: 1,
    id: 17,
  },

  18: {
    compartment: "comp_3",
    stock: 20,
    maxStock: 30,
    width: 2,
    warehouse: 1,
    id: 18,
  },
  19: {
    compartment: "comp_4",
    stock: 20,
    maxStock: 30,
    width: 2,
    warehouse: 1,
    id: 19,
  },

  20: {
    compartment: "comp_4",
    stock: 20,
    maxStock: 30,
    width: 2,
    warehouse: 1,
    id: 20,
  },

  21: {
    compartment: "comp_5",
    stock: 20,
    maxStock: 30,
    width: 2,
    warehouse: 1,
    id: 21,
  },

  22: {
    compartment: "comp_5",
    stock: 10,
    maxStock: 30,
    width: 2,
    warehouse: 1,
    id: 22,
  },

  23: {
    compartment: "comp_6",
    stock: 20,
    maxStock: 30,
    width: 2,
    warehouse: 1,
    id: 23,
  },

  24: {
    compartment: "comp_6",
    stock: 10,
    maxStock: 30,
    width: 2,
    warehouse: 1,
    id: 24,
  },
  25: {
    compartment: "comp_6",
    stock: 0,
    maxStock: 30,
    width: 2,
    warehouse: 1,
    id: 25,
  },

  26: {
    compartment: "comp_7",
    stock: 10,
    maxStock: 30,
    width: 5,
    warehouse: 1,
    id: 26,
  },
  27: {
    compartment: "comp_7",
    stock: 0,
    maxStock: 30,
    width: 5,
    warehouse: 1,
    id: 27,
  },
  28: {
    compartment: "comp_8",
    stock: 10,
    maxStock: 30,
    width: 5,
    warehouse: 1,
    id: 28,
  },
  29: {
    compartment: "comp_8",
    stock: 5,
    maxStock: 30,
    width: 5,
    warehouse: 1,
    id: 29,
  },
  30: {
    compartment: "comp_8",
    stock: 26,
    maxStock: 30,
    width: 5,
    warehouse: 1,
    id: 30,
  },
  31: {
    compartment: "comp_8",
    stock: 9,
    maxStock: 30,
    width: 5,
    warehouse: 1,
    id: 31,
  },
  32: {
    compartment: "comp_8",
    stock: 0,
    maxStock: 30,
    width: 5,
    warehouse: 1,
    id: 32,
  },
};

export const compartments = {
  comp_1: {
    name: "comp_1",
    width: 40,
    height: 44,
    direction: "column",
    color: "#ddd",
    position: { top: 0, left: 0 },
    realPosition: "top",
  },
  comp_2: {
    name: "comp_2",
    width: 40,
    height: 44,
    direction: "column",
    color: "#ddd",
    position: { top: 56, left: 0 },
    realPosition: "bottom",
  },

  divider_1: {
    name: "divider_1",
    width: 0.5,
    height: 100,
    direction: "column",
    color: "black",
    position: { top: 0, left: 40 },
    realPosition: "",
  },

  comp_3: {
    name: "comp_3",
    width: 10,
    height: 44,
    direction: "row",
    color: "#ddd",
    position: { top: 0, left: 40.5 },
    realPosition: "bottom",
  },

  comp_4: {
    name: "comp_4",
    width: 10,
    height: 44,
    direction: "row",
    color: "#ddd",
    position: { top: 56, left: 40.5 },
    realPosition: "bottom",
  },

  comp_5: {
    name: "comp_5",
    width: 10,
    height: 44,
    direction: "row",
    color: "#ddd",
    position: { top: 0, left: 56 },
    realPosition: "top",
  },

  comp_6: {
    name: "comp_6",
    width: 10,
    height: 44,
    direction: "row",
    color: "#ddd",
    position: { top: 56, left: 56 },
    realPosition: "top",
  },

  divider_2: {
    name: "divider_1",
    width: 0.5,
    height: 100,
    direction: "column",
    color: "black",
    position: { top: 0, left: 66 },
    realPosition: "",
  },

  comp_7: {
    name: "comp_7",
    width: 33.4,
    height: 44,
    direction: "column",
    color: "#ddd",
    position: { top: 0, left: 66.6 },
    realPosition: "top",
  },

  comp_8: {
    name: "comp_8",
    width: 33.4,
    height: 44,
    direction: "column",
    color: "#ddd",
    position: { top: 56, left: 66.6 },
    realPosition: "bottom",
  },
};
