import { EURO, INDUSTRY } from "./auslagerung/createTour/constants";

export const products = [
  {
    id: 1,
    product_id: "227445",
    product_name: "Flachkannen",
    type: EURO,
  },
  {
    id: 2,
    product_id: "223657",
    product_name: "Polykanister",
    type: EURO,
  },
  {
    id: 3,
    product_id: "2297500",
    product_name: "CP3 Paletten",
    type: INDUSTRY,
  },
];

export const customers = [
  {
    id: 1,
    customer_id: "37HOSTIE",
    customer_name: "Stitebel Eltron",
  },
  {
    id: 2,
    customer_id: "57ERAST00",
    customer_name: "AST",
  },
];

export const einlagerungen = [
  {
    id: 1,
    customer_id: "37HOSTIE00",
    product_id: 2274254,
    product_name: "Flachkannen",
    quantity: 300,
    datetime: "2020-04-03 16:01:00",
    employee_name: "Fricke, Torben",
    employee_id: 1,
    storage: "Halle 2",
    row_name: "C42",
    row_id: 1,
    notes: "",
  },
  {
    id: 2,
    customer_id: "47MOPETE00",
    product_id: 235800,
    product_name: "Polykanister EVOH",
    quantity: 260,
    datetime: "2020-04-03 14:01:00",
    employee_name: "Fricke, Torben",
    employee_id: 1,
    storage: "Halle 3 / Halle 2",
    row_name: "C38",
    row_id: 2,
    notes: "",
  },
  {
    id: 3,
    customer_id: "37HOSYMR00",
    product_id: 279000,
    product_name: "Sickenfässer Palettiert",
    quantity: 192,
    datetime: "2020-04-03 14:01:00",
    employee_id: null,
    employee_name: null,
    storage: "Brücke",
    row_name: "Br. 122",
    row_id: 3,
    notes: "",
  },
];

export const auslagerungen = [
  {
    id: 1,
    customer_id: "37HOSYMR00",
    product_id: 2274254,
    product_name: "Flachkannen",
    quantity: 300,
    datetime: "2020-04-03 15:01:00",
    employee_name: "Spadi, Victor",
    employee_id: 5,
    storage: "Halle 2",
    row_name: "C42",
    row_id: 1,
    notes: "",
    tour_id: 1,
    tour_number: 1,
  },
  {
    id: 2,
    customer_id: "37HOSYMR00",
    product_id: 2274252,
    product_name: "Europaletten",
    quantity: 119,
    datetime: "2020-04-03 15:01:00",
    employee_name: "Spadi, Victor",
    employee_id: 5,
    storage: "Halle 4",
    row_name: "D5",
    row_id: 2,
    notes: "",
    tour_id: 1,
    tour_number: 1,
  },
  {
    id: 3,
    customer_id: "37HOSYMR00",
    product_id: 2274252,
    product_name: "Europaletten",
    quantity: 119,
    datetime: "2020-04-03 17:01:00",
    employee_name: "Hein, Robert",
    employee_id: 5,
    storage: "Halle 4",
    row_name: "D5",
    row_id: 2,
    notes: "",
    tour_id: 2,
    tour_number: 2,
  },
  {
    id: 4,
    customer_id: "37HOSYMR00",
    product_id: 2274252,
    product_name: "Europaletten",
    quantity: 119,
    datetime: "2020-04-03 17:01:00",
    employee_name: "Hein, Robert",
    employee_id: 5,
    storage: "Halle 4",
    row_name: "D5",
    row_id: 2,
    notes: "",
    tour_id: 2,
    tour_number: 2,
  },
];

export const storageBridges = [
  { bridge_id: "01", bridge_number: "Brücke Nr. 1", isEmpty: true },
  { bridge_id: "122", bridge_number: "Brücke Nr.122", isEmpty: true },
  {
    bridge_id: "222",
    bridge_number: "Brücke Nr.222",
    isEmpty: false,
    prduct_id: 2790000,
    datetime: "2020-01-01 12:00:00",
    type_id: 1,
  },
];

// export const storage = [
//   {
//     row_id: 1,
//     row_name: "C42",
//     storage: 3,
//     open: 10,
//     isEmpty: false,
//     isFull: false,
//   },
//   {
//     row_id: 2,
//     row_name: "C38",
//     storage: 3,
//     open: 100,
//     isEmpty: true,
//     isFull: false,
//   },
//   {
//     row_id: 4,
//     row_name: "D22",
//     storage: 4,
//     open: 500,
//     isEmpty: true,
//     isFull: false,
//   },
// ];

export const employees = [
  { employee_id: "1", employee_name: "Fricke, Torben" },
  { employee_id: "2", employee_name: "Jagata, Maurice" },
  { employe__id: "3", employee_name: "Sylla, Ibrahima" },
];

export const symBuildings = [
  { symBuilding_id: "1", symBuilding_name: "X442", symFactory_id: 1 },
  { symBuilding_id: "2", symBuilding_name: "C50", symFactory_id: 2 },
  { symBuilding_id: "3", symBuilding_name: "Y500", symFactory_id: 1 },
];

export const storage = [
  {
    compartment: "comp_1",
    product_id: 2276312,
    product_name: "Polykanister",
    open: 0,
    isEmpty: true,
    isFull: false,
    stock: 30,
    row_name: "H44",
    warehouse_name: "Halle 2",
    maxStock: 30,
    width: 5,
    warehouse_id: 2,
    row_id: 1,
  },
  {
    compartment: "comp_1",
    product_id: 2276312,
    product_name: "Polykanister",
    open: 30,
    isEmpty: true,
    isFull: false,
    stock: 0,
    row_name: "H44",
    warehouse_name: "Halle 2",
    maxStock: 30,
    width: 5,
    warehouse_id: 2,
    row_id: 2,
  },
  {
    compartment: "comp_1",
    product_id: 2276312,
    product_name: "Polykanister",
    open: 15,
    isEmpty: true,
    isFull: false,
    stock: 15,
    row_name: "H44",
    warehouse_name: "Halle 2",
    maxStock: 30,
    width: 5,
    warehouse_id: 2,
    row_id: 3,
  },
  {
    compartment: "comp_1",
    product_id: 2276312,
    product_name: "Polykanister",
    open: 5,
    isEmpty: true,
    isFull: false,
    stock: 25,
    row_name: "H44",
    warehouse_name: "Halle 2",
    maxStock: 30,
    width: 5,
    warehouse_id: 2,
    row_id: 4,
  },
  // {
  //   compartment: "comp_1",
  //   product_id: 2276312,
  //   product_name: "Polykanister",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 10,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 5,
  //   warehouse_id: 2,
  //   row_id: 5,
  // },
  // {
  //   compartment: "comp_1",
  //   product_id: 2276312,
  //   product_name: "Polykanister",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 20,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 5,
  //   warehouse_id: 2,
  //   row_id: 6,
  // },
  // {
  //   compartment: "comp_1",
  //   product_id: 2276312,
  //   product_name: "Polykanister",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 20,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 5,
  //   warehouse_id: 2,
  //   row_id: 7,
  // },

  // {
  //   compartment: "comp_2",
  //   product_id: 2316312,
  //   product_name: "Polykanister",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 0,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 5,
  //   warehouse_id: 2,
  //   row_id: 8,
  // },
  // {
  //   compartment: "comp_2",
  //   product_id: 2316312,
  //   product_name: "Polykanister",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 30,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 5,
  //   warehouse_id: 2,
  //   row_id: 9,
  // },
  // {
  //   compartment: "comp_2",
  //   product_id: 2316312,
  //   product_name: "Polykanister",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 10,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 5,
  //   warehouse_id: 2,
  //   row_id: 10,
  // },
  // {
  //   compartment: "comp_2",
  //   product_id: 2316312,
  //   product_name: "Polykanister",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 20,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 5,
  //   warehouse_id: 2,
  //   row_id: 11,
  // },
  // {
  //   compartment: "comp_2",
  //   product_id: 2316312,
  //   product_name: "Polykanister",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 20,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 5,
  //   warehouse_id: 2,
  //   row_id: 12,
  // },

  // {
  //   compartment: "comp_2",
  //   product_id: 2316312,
  //   product_name: "Polykanister",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 20,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 5,
  //   warehouse_id: 2,
  //   row_id: 13,
  // },

  // {
  //   compartment: "comp_2",
  //   product_id: 2316312,
  //   product_name: "",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 20,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 5,
  //   warehouse_id: 2,
  //   row_id: 14,
  // },

  // {
  //   compartment: "comp_3",
  //   product_id: 2976312,
  //   product_name: "",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 20,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 2,
  //   warehouse_id: 2,
  //   row_id: 15,
  // },

  // {
  //   compartment: "comp_3",
  //   product_id: 2976312,
  //   product_name: "",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 20,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 2,
  //   warehouse_id: 2,
  //   row_id: 16,
  // },

  // {
  //   compartment: "comp_3",
  //   product_id: 2976312,
  //   product_name: "",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 20,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 2,
  //   warehouse_id: 2,
  //   row_id: 17,
  // },

  // {
  //   compartment: "comp_3",
  //   product_id: 2976312,
  //   product_name: "",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 20,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 2,
  //   warehouse_id: 2,
  //   row_id: 18,
  // },
  // {
  //   compartment: "comp_4",
  //   product_id: 2076312,
  //   product_name: "",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 20,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 2,
  //   warehouse_id: 2,
  //   row_id: 19,
  // },

  // {
  //   compartment: "comp_4",
  //   product_id: 2076312,
  //   product_name: "",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 20,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 2,
  //   warehouse_id: 2,
  //   row_id: 20,
  // },

  // {
  //   compartment: "comp_5",
  //   product_id: 2766312,
  //   product_name: "",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 20,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 2,
  //   warehouse_id: 2,
  //   row_id: 21,
  // },

  // {
  //   compartment: "comp_5",
  //   product_id: 2766312,
  //   product_name: "",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 10,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 2,
  //   warehouse_id: 2,
  //   row_id: 22,
  // },

  // {
  //   compartment: "comp_6",
  //   product_id: 2766312,
  //   product_name: "",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 20,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 2,
  //   warehouse_id: 2,
  //   row_id: 23,
  // },

  // {
  //   compartment: "comp_6",
  //   product_id: 2766312,
  //   product_name: "",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 10,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 2,
  //   warehouse_id: 2,
  //   row_id: 24,
  // },
  // {
  //   compartment: "comp_6",
  //   product_id: 2766312,
  //   product_name: "",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 10,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 2,
  //   warehouse_id: 2,
  //   row_id: 25,
  // },
  // {
  //   compartment: "comp_7",
  //   product_id: 2766358,
  //   product_name: "Flachkannen",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 10,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 5,
  //   warehouse_id: 2,
  //   row_id: 26,
  // },
  // {
  //   compartment: "comp_7",
  //   product_id: 2766358,
  //   product_name: "Flachkannen",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 0,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 5,
  //   warehouse_id: 2,
  //   row_id: 27,
  // },
  // {
  //   compartment: "comp_8",
  //   product_id: 2744558,
  //   product_name: "",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 10,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 5,
  //   warehouse_id: 2,
  //   row_id: 28,
  // },
  // {
  //   compartment: "comp_8",
  //   product_id: 2744558,
  //   product_name: "CP3 Paletten",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 5,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 5,
  //   warehouse_id: 2,
  //   row_id: 29,
  // },
  // {
  //   compartment: "comp_8",
  //   product_id: 2744558,
  //   product_name: "CP3 Paletten",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 26,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 5,
  //   warehouse_id: 2,
  //   row_id: 30,
  // },
  // {
  //   compartment: "comp_8",
  //   product_id: 2744558,
  //   product_name: "CP3 Paletten",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 9,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 5,
  //   warehouse_id: 2,
  //   row_id: 31,
  // },
  // {
  //   compartment: "comp_8",
  //   product_id: 2744558,
  //   product_name: "CP3 Paletten",
  //   open: 12,
  //   isEmpty: true,
  //   isFull: false,
  //   stock: 0,
  //   row_name: "H44",
  //   warehouse_name: "Halle 2",
  //   maxStock: 30,
  //   width: 5,
  //   warehouse_id: 2,
  //   row_id: 32,
  // },
];

export const compartments = [
  {
    name: "comp_1",
    width: 40,
    height: 44,
    direction: "column",
    color: "#ddd",
    position: { top: 0, left: 0 },
    warehouse_id: 2,
    realPosition: "top",
  },
  {
    name: "comp_2",
    width: 40,
    height: 44,
    direction: "column",
    color: "#ddd",
    position: { top: 56, left: 0 },
    warehouse_id: 2,
    realPosition: "bottom",
  },

  {
    name: "divider_1",
    width: 0.5,
    height: 100,
    direction: "column",
    color: "black",
    position: { top: 0, left: 40 },
    warehouse_id: 2,
    realPosition: "",
  },

  {
    name: "comp_3",
    width: 10,
    height: 44,
    direction: "row",
    color: "#ddd",
    position: { top: 0, left: 40.5 },
    warehouse_id: 2,
    realPosition: "bottom",
  },

  {
    name: "comp_4",
    width: 10,
    height: 44,
    direction: "row",
    color: "#ddd",
    position: { top: 56, left: 40.5 },
    warehouse_id: 2,
    realPosition: "bottom",
  },

  {
    name: "comp_5",
    width: 10,
    height: 44,
    direction: "row",
    color: "#ddd",
    position: { top: 0, left: 56 },
    warehouse_id: 2,
    realPosition: "top",
  },

  {
    name: "comp_6",
    width: 10,
    height: 44,
    direction: "row",
    color: "#ddd",
    position: { top: 56, left: 56 },
    warehouse_id: 2,
    realPosition: "top",
  },

  {
    name: "divider_1",
    width: 0.5,
    height: 100,
    direction: "column",
    color: "black",
    position: { top: 0, left: 66 },
    warehouse_id: 2,
    realPosition: "",
  },

  {
    name: "comp_7",
    width: 33.4,
    height: 44,
    direction: "column",
    color: "#ddd",
    position: { top: 0, left: 66.6 },
    warehouse_id: 2,
    realPosition: "top",
  },
  {
    name: "comp_8",
    width: 33.4,
    height: 44,
    direction: "column",
    color: "#ddd",
    position: { top: 56, left: 66.6 },
    warehouse_id: 2,
    realPosition: "bottom",
  },
];

// export const warehouse = {
//   2: {
//     rows: rows,
//     rows_: {
//       1: {
//         compartment: "comp_1",
//         product_id: 2276312,
//         product_name: "Polykanister",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 9,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 5,
//         warehouse_id: 2,
//         row_id: 1,
//       },
//       2: {
//         compartment: "comp_1",
//         product_id: 2276312,
//         product_name: "Polykanister",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 0,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 5,
//         warehouse_id: 2,
//         row_id: 2,
//       },
//       3: {
//         compartment: "comp_1",
//         product_id: 2276312,
//         product_name: "Polykanister",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 20,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 5,
//         warehouse_id: 2,
//         row_id: 3,
//       },
//       4: {
//         compartment: "comp_1",
//         product_id: 2276312,
//         product_name: "Polykanister",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 9,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 5,
//         warehouse_id: 2,
//         row_id: 4,
//       },
//       5: {
//         compartment: "comp_1",
//         product_id: 2276312,
//         product_name: "Polykanister",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 10,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 5,
//         warehouse_id: 2,
//         row_id: 5,
//       },
//       6: {
//         compartment: "comp_1",
//         product_id: 2276312,
//         product_name: "Polykanister",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 20,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 5,
//         warehouse_id: 2,
//         row_id: 6,
//       },
//       7: {
//         compartment: "comp_1",
//         product_id: 2276312,
//         product_name: "Polykanister",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 20,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 5,
//         warehouse_id: 2,
//         row_id: 7,
//       },

//       8: {
//         compartment: "comp_2",
//         product_id: 2316312,
//         product_name: "Polykanister",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 0,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 5,
//         warehouse_id: 2,
//         row_id: 8,
//       },
//       9: {
//         compartment: "comp_2",
//         product_id: 2316312,
//         product_name: "Polykanister",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 30,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 5,
//         warehouse_id: 2,
//         row_id: 9,
//       },
//       10: {
//         compartment: "comp_2",
//         product_id: 2316312,
//         product_name: "Polykanister",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 10,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 5,
//         warehouse_id: 2,
//         row_id: 10,
//       },
//       11: {
//         compartment: "comp_2",
//         product_id: 2316312,
//         product_name: "Polykanister",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 20,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 5,
//         warehouse_id: 2,
//         row_id: 11,
//       },
//       12: {
//         compartment: "comp_2",
//         product_id: 2316312,
//         product_name: "Polykanister",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 20,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 5,
//         warehouse_id: 2,
//         row_id: 12,
//       },

//       13: {
//         compartment: "comp_2",
//         product_id: 2316312,
//         product_name: "Polykanister",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 20,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 5,
//         warehouse_id: 2,
//         row_id: 13,
//       },

//       14: {
//         compartment: "comp_2",
//         product_id: 2316312,
//         product_name: "",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 20,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 5,
//         warehouse_id: 2,
//         row_id: 14,
//       },

//       15: {
//         compartment: "comp_3",
//         product_id: 2976312,
//         product_name: "",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 20,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 2,
//         warehouse_id: 2,
//         row_id: 15,
//       },

//       16: {
//         compartment: "comp_3",
//         product_id: 2976312,
//         product_name: "",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 20,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 2,
//         warehouse_id: 2,
//         row_id: 16,
//       },

//       17: {
//         compartment: "comp_3",
//         product_id: 2976312,
//         product_name: "",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 20,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 2,
//         warehouse_id: 2,
//         row_id: 17,
//       },

//       18: {
//         compartment: "comp_3",
//         product_id: 2976312,
//         product_name: "",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 20,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 2,
//         warehouse_id: 2,
//         row_id: 18,
//       },
//       19: {
//         compartment: "comp_4",
//         product_id: 2076312,
//         product_name: "",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 20,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 2,
//         warehouse_id: 2,
//         row_id: 19,
//       },

//       20: {
//         compartment: "comp_4",
//         product_id: 2076312,
//         product_name: "",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 20,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 2,
//         warehouse_id: 2,
//         row_id: 20,
//       },

//       21: {
//         compartment: "comp_5",
//         product_id: 2766312,
//         product_name: "",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 20,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 2,
//         warehouse_id: 2,
//         row_id: 21,
//       },

//       22: {
//         compartment: "comp_5",
//         product_id: 2766312,
//         product_name: "",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 10,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 2,
//         warehouse_id: 2,
//         row_id: 22,
//       },

//       23: {
//         compartment: "comp_6",
//         product_id: 2766312,
//         product_name: "",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 20,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 2,
//         warehouse_id: 2,
//         row_id: 23,
//       },

//       24: {
//         compartment: "comp_6",
//         product_id: 2766312,
//         product_name: "",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 10,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 2,
//         warehouse_id: 2,
//         row_id: 24,
//       },
//       25: {
//         compartment: "comp_6",
//         product_id: 2766312,
//         product_name: "",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 10,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 2,
//         warehouse_id: 2,
//         row_id: 25,
//       },
//       26: {
//         compartment: "comp_7",
//         product_id: 2766358,
//         product_name: "Flachkannen",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 10,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 5,
//         warehouse_id: 2,
//         row_id: 26,
//       },
//       27: {
//         compartment: "comp_7",
//         product_id: 2766358,
//         product_name: "Flachkannen",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 0,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 5,
//         warehouse_id: 2,
//         row_id: 27,
//       },
//       28: {
//         compartment: "comp_8",
//         product_id: 2744558,
//         product_name: "",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 10,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 5,
//         warehouse_id: 2,
//         row_id: 28,
//       },
//       29: {
//         compartment: "comp_8",
//         product_id: 2744558,
//         product_name: "CP3 Paletten",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 5,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 5,
//         warehouse_id: 2,
//         row_id: 29,
//       },
//       30: {
//         compartment: "comp_8",
//         product_id: 2744558,
//         product_name: "CP3 Paletten",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 26,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 5,
//         warehouse_id: 2,
//         row_id: 30,
//       },
//       31: {
//         compartment: "comp_8",
//         product_id: 2744558,
//         product_name: "CP3 Paletten",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 9,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 5,
//         warehouse_id: 2,
//         row_id: 31,
//       },
//       32: {
//         compartment: "comp_8",
//         product_id: 2744558,
//         product_name: "CP3 Paletten",
//         open: 12,
//         isEmpty: true,
//         isFull: false,
//         stock: 0,
//         row_name: "H44", warehouse_name: "Halle 2", maxStock: 30,
//         width: 5,
//         warehouse_id: 2,
//         row_id: 32,
//       },
//     },

//     compartments: {
//       comp_1: {
//         name: "comp_1",
//         width: 40,
//         height: 44,
//         direction: "column",
//         color: "#ddd",
//         position: { top: 0, left: 0 },
//         warehouse_id: 2 ,realPosition: "top",
//       },
//       comp_2: {
//         name: "comp_2",
//         width: 40,
//         height: 44,
//         direction: "column",
//         color: "#ddd",
//         position: { top: 56, left: 0 },
//         warehouse_id: 2 ,realPosition: "bottom",
//       },

//       divider_1: {
//         name: "divider_1",
//         width: 0.5,
//         height: 100,
//         direction: "column",
//         color: "black",
//         position: { top: 0, left: 40 },
//         warehouse_id: 2 ,realPosition: "",
//       },

//       comp_3: {
//         name: "comp_3",
//         width: 10,
//         height: 44,
//         direction: "row",
//         color: "#ddd",
//         position: { top: 0, left: 40.5 },
//         warehouse_id: 2 ,realPosition: "bottom",
//       },

//       comp_4: {
//         name: "comp_4",
//         width: 10,
//         height: 44,
//         direction: "row",
//         color: "#ddd",
//         position: { top: 56, left: 40.5 },
//         warehouse_id: 2 ,realPosition: "bottom",
//       },

//       comp_5: {
//         name: "comp_5",
//         width: 10,
//         height: 44,
//         direction: "row",
//         color: "#ddd",
//         position: { top: 0, left: 56 },
//         warehouse_id: 2 ,realPosition: "top",
//       },

//       comp_6: {
//         name: "comp_6",
//         width: 10,
//         height: 44,
//         direction: "row",
//         color: "#ddd",
//         position: { top: 56, left: 56 },
//         warehouse_id: 2 ,realPosition: "top",
//       },

//       divider_2: {
//         name: "divider_1",
//         width: 0.5,
//         height: 100,
//         direction: "column",
//         color: "black",
//         position: { top: 0, left: 66 },
//         warehouse_id: 2 ,realPosition: "",
//       },

//       comp_7: {
//         name: "comp_7",
//         width: 33.4,
//         height: 44,
//         direction: "column",
//         color: "#ddd",
//         position: { top: 0, left: 66.6 },
//         warehouse_id: 2 ,realPosition: "top",
//       },

//       comp_8: {
//         name: "comp_8",
//         width: 33.4,
//         height: 44,
//         direction: "column",
//         color: "#ddd",
//         position: { top: 56, left: 66.6 },
//         warehouse_id: 2 ,realPosition: "bottom",
//       },
//     },
//   },
// };
